version: '3.9'
services:
  mongodb:
    container_name: mongodb
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db
  api:
    container_name: movies
    image: movies:1.0
    build: .
    ports:
      - ${APP_PORT}:${APP_PORT}
    env_file:
      - .env
    depends_on:
      - mongodb
volumes:
  mongodb_data: { }
